services: 
  app: 
    build: .
    container_name: manajement_hutang
    volumes:
      - .:/var/www/html
    networks:
      - ci4-network
    environment:
      CI_ENVIRONMENT: development
      APP_BASE_URL: http://localhost:8000
  web: 
    image: nginx:alpine
    container_name: manajemen_hutang_nginx
    ports:
    - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ci4-network
  mysql:
    image: mysql:8.0
    container_name: manajemen_hutang_mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: manajemen_hutang
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ci4-network
volumes: 
  mysql-data:
networks:
  ci4-network:
    driver: bridge
